# This rule is not used by the project disaggregatedset itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over disaggregatedset.x-k8s.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: disaggregatedset
    app.kubernetes.io/managed-by: kustomize
  name: disaggregatedset-admin-role
rules:
- apiGroups:
  - disaggregatedset.x-k8s.io
  resources:
  - disaggregatedsets
  verbs:
  - '*'
- apiGroups:
  - disaggregatedset.x-k8s.io
  resources:
  - disaggregatedsets/status
  verbs:
  - get
