apiVersion: config.lws.x-k8s.io/v1alpha1
kind: Configuration
leaderElection:
  leaderElect: true
internalCertManagement:
  enable: true
# If you want to enable gang scheduling, you need to uncomment the following section(take volcano as an example)
# gangSchedulingManagement:
#   schedulerProvider: volcano
