/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package v1alpha1 contains API Schema definitions for the lws v1alpha1 API group
// +kubebuilder:object:generate=true
// +groupName=lws.x-k8s.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "config.lws.x-k8s.io", Version: "v1alpha1"}

	// localSchemeBuilder is used to register autogenerated conversion and defaults functions
	// It is required by ./zz_generated.conversion.go and ./zz_generated.defaults.go
	localSchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes, RegisterDefaults)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = localSchemeBuilder.AddToScheme
)

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(GroupVersion, &Configuration{})
	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
}
