//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "sigs.k8s.io/lws/api/config/v1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClientConnection)(nil), (*v1.ClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClientConnection_To_v1_ClientConnection(a.(*ClientConnection), b.(*v1.ClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ClientConnection)(nil), (*ClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClientConnection_To_v1alpha1_ClientConnection(a.(*v1.ClientConnection), b.(*ClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*v1.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_v1_Configuration(a.(*Configuration), b.(*v1.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Configuration_To_v1alpha1_Configuration(a.(*v1.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerHealth)(nil), (*v1.ControllerHealth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerHealth_To_v1_ControllerHealth(a.(*ControllerHealth), b.(*v1.ControllerHealth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ControllerHealth)(nil), (*ControllerHealth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ControllerHealth_To_v1alpha1_ControllerHealth(a.(*v1.ControllerHealth), b.(*ControllerHealth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerManager)(nil), (*v1.ControllerManager)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerManager_To_v1_ControllerManager(a.(*ControllerManager), b.(*v1.ControllerManager), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ControllerManager)(nil), (*ControllerManager)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ControllerManager_To_v1alpha1_ControllerManager(a.(*v1.ControllerManager), b.(*ControllerManager), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerMetrics)(nil), (*v1.ControllerMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerMetrics_To_v1_ControllerMetrics(a.(*ControllerMetrics), b.(*v1.ControllerMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ControllerMetrics)(nil), (*ControllerMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ControllerMetrics_To_v1alpha1_ControllerMetrics(a.(*v1.ControllerMetrics), b.(*ControllerMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerWebhook)(nil), (*v1.ControllerWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerWebhook_To_v1_ControllerWebhook(a.(*ControllerWebhook), b.(*v1.ControllerWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ControllerWebhook)(nil), (*ControllerWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ControllerWebhook_To_v1alpha1_ControllerWebhook(a.(*v1.ControllerWebhook), b.(*ControllerWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GangSchedulingManagement)(nil), (*v1.GangSchedulingManagement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GangSchedulingManagement_To_v1_GangSchedulingManagement(a.(*GangSchedulingManagement), b.(*v1.GangSchedulingManagement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.GangSchedulingManagement)(nil), (*GangSchedulingManagement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GangSchedulingManagement_To_v1alpha1_GangSchedulingManagement(a.(*v1.GangSchedulingManagement), b.(*GangSchedulingManagement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InternalCertManagement)(nil), (*v1.InternalCertManagement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InternalCertManagement_To_v1_InternalCertManagement(a.(*InternalCertManagement), b.(*v1.InternalCertManagement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.InternalCertManagement)(nil), (*InternalCertManagement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_InternalCertManagement_To_v1alpha1_InternalCertManagement(a.(*v1.InternalCertManagement), b.(*InternalCertManagement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSOptions)(nil), (*v1.TLSOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSOptions_To_v1_TLSOptions(a.(*TLSOptions), b.(*v1.TLSOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.TLSOptions)(nil), (*TLSOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TLSOptions_To_v1alpha1_TLSOptions(a.(*v1.TLSOptions), b.(*TLSOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClientConnection_To_v1_ClientConnection(in *ClientConnection, out *v1.ClientConnection, s conversion.Scope) error {
	*out = *(*v1.ClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ClientConnection_To_v1_ClientConnection is an autogenerated conversion function.
func Convert_v1alpha1_ClientConnection_To_v1_ClientConnection(in *ClientConnection, out *v1.ClientConnection, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClientConnection_To_v1_ClientConnection(in, out, s)
}

func autoConvert_v1_ClientConnection_To_v1alpha1_ClientConnection(in *v1.ClientConnection, out *ClientConnection, s conversion.Scope) error {
	*out = *(*ClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ClientConnection_To_v1alpha1_ClientConnection is an autogenerated conversion function.
func Convert_v1_ClientConnection_To_v1alpha1_ClientConnection(in *v1.ClientConnection, out *ClientConnection, s conversion.Scope) error {
	return autoConvert_v1_ClientConnection_To_v1alpha1_ClientConnection(in, out, s)
}

func autoConvert_v1alpha1_Configuration_To_v1_Configuration(in *Configuration, out *v1.Configuration, s conversion.Scope) error {
	if err := Convert_v1alpha1_ControllerManager_To_v1_ControllerManager(&in.ControllerManager, &out.ControllerManager, s); err != nil {
		return err
	}
	out.InternalCertManagement = (*v1.InternalCertManagement)(unsafe.Pointer(in.InternalCertManagement))
	out.GangSchedulingManagement = (*v1.GangSchedulingManagement)(unsafe.Pointer(in.GangSchedulingManagement))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.ClientConnection = (*v1.ClientConnection)(unsafe.Pointer(in.ClientConnection))
	return nil
}

// Convert_v1alpha1_Configuration_To_v1_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_v1_Configuration(in *Configuration, out *v1.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_v1_Configuration(in, out, s)
}

func autoConvert_v1_Configuration_To_v1alpha1_Configuration(in *v1.Configuration, out *Configuration, s conversion.Scope) error {
	if err := Convert_v1_ControllerManager_To_v1alpha1_ControllerManager(&in.ControllerManager, &out.ControllerManager, s); err != nil {
		return err
	}
	out.InternalCertManagement = (*InternalCertManagement)(unsafe.Pointer(in.InternalCertManagement))
	out.GangSchedulingManagement = (*GangSchedulingManagement)(unsafe.Pointer(in.GangSchedulingManagement))
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	out.ClientConnection = (*ClientConnection)(unsafe.Pointer(in.ClientConnection))
	return nil
}

// Convert_v1_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_v1_Configuration_To_v1alpha1_Configuration(in *v1.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_v1_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_ControllerHealth_To_v1_ControllerHealth(in *ControllerHealth, out *v1.ControllerHealth, s conversion.Scope) error {
	*out = *(*v1.ControllerHealth)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControllerHealth_To_v1_ControllerHealth is an autogenerated conversion function.
func Convert_v1alpha1_ControllerHealth_To_v1_ControllerHealth(in *ControllerHealth, out *v1.ControllerHealth, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerHealth_To_v1_ControllerHealth(in, out, s)
}

func autoConvert_v1_ControllerHealth_To_v1alpha1_ControllerHealth(in *v1.ControllerHealth, out *ControllerHealth, s conversion.Scope) error {
	*out = *(*ControllerHealth)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ControllerHealth_To_v1alpha1_ControllerHealth is an autogenerated conversion function.
func Convert_v1_ControllerHealth_To_v1alpha1_ControllerHealth(in *v1.ControllerHealth, out *ControllerHealth, s conversion.Scope) error {
	return autoConvert_v1_ControllerHealth_To_v1alpha1_ControllerHealth(in, out, s)
}

func autoConvert_v1alpha1_ControllerManager_To_v1_ControllerManager(in *ControllerManager, out *v1.ControllerManager, s conversion.Scope) error {
	*out = *(*v1.ControllerManager)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControllerManager_To_v1_ControllerManager is an autogenerated conversion function.
func Convert_v1alpha1_ControllerManager_To_v1_ControllerManager(in *ControllerManager, out *v1.ControllerManager, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerManager_To_v1_ControllerManager(in, out, s)
}

func autoConvert_v1_ControllerManager_To_v1alpha1_ControllerManager(in *v1.ControllerManager, out *ControllerManager, s conversion.Scope) error {
	*out = *(*ControllerManager)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ControllerManager_To_v1alpha1_ControllerManager is an autogenerated conversion function.
func Convert_v1_ControllerManager_To_v1alpha1_ControllerManager(in *v1.ControllerManager, out *ControllerManager, s conversion.Scope) error {
	return autoConvert_v1_ControllerManager_To_v1alpha1_ControllerManager(in, out, s)
}

func autoConvert_v1alpha1_ControllerMetrics_To_v1_ControllerMetrics(in *ControllerMetrics, out *v1.ControllerMetrics, s conversion.Scope) error {
	*out = *(*v1.ControllerMetrics)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControllerMetrics_To_v1_ControllerMetrics is an autogenerated conversion function.
func Convert_v1alpha1_ControllerMetrics_To_v1_ControllerMetrics(in *ControllerMetrics, out *v1.ControllerMetrics, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerMetrics_To_v1_ControllerMetrics(in, out, s)
}

func autoConvert_v1_ControllerMetrics_To_v1alpha1_ControllerMetrics(in *v1.ControllerMetrics, out *ControllerMetrics, s conversion.Scope) error {
	*out = *(*ControllerMetrics)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ControllerMetrics_To_v1alpha1_ControllerMetrics is an autogenerated conversion function.
func Convert_v1_ControllerMetrics_To_v1alpha1_ControllerMetrics(in *v1.ControllerMetrics, out *ControllerMetrics, s conversion.Scope) error {
	return autoConvert_v1_ControllerMetrics_To_v1alpha1_ControllerMetrics(in, out, s)
}

func autoConvert_v1alpha1_ControllerWebhook_To_v1_ControllerWebhook(in *ControllerWebhook, out *v1.ControllerWebhook, s conversion.Scope) error {
	*out = *(*v1.ControllerWebhook)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControllerWebhook_To_v1_ControllerWebhook is an autogenerated conversion function.
func Convert_v1alpha1_ControllerWebhook_To_v1_ControllerWebhook(in *ControllerWebhook, out *v1.ControllerWebhook, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerWebhook_To_v1_ControllerWebhook(in, out, s)
}

func autoConvert_v1_ControllerWebhook_To_v1alpha1_ControllerWebhook(in *v1.ControllerWebhook, out *ControllerWebhook, s conversion.Scope) error {
	*out = *(*ControllerWebhook)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ControllerWebhook_To_v1alpha1_ControllerWebhook is an autogenerated conversion function.
func Convert_v1_ControllerWebhook_To_v1alpha1_ControllerWebhook(in *v1.ControllerWebhook, out *ControllerWebhook, s conversion.Scope) error {
	return autoConvert_v1_ControllerWebhook_To_v1alpha1_ControllerWebhook(in, out, s)
}

func autoConvert_v1alpha1_GangSchedulingManagement_To_v1_GangSchedulingManagement(in *GangSchedulingManagement, out *v1.GangSchedulingManagement, s conversion.Scope) error {
	*out = *(*v1.GangSchedulingManagement)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_GangSchedulingManagement_To_v1_GangSchedulingManagement is an autogenerated conversion function.
func Convert_v1alpha1_GangSchedulingManagement_To_v1_GangSchedulingManagement(in *GangSchedulingManagement, out *v1.GangSchedulingManagement, s conversion.Scope) error {
	return autoConvert_v1alpha1_GangSchedulingManagement_To_v1_GangSchedulingManagement(in, out, s)
}

func autoConvert_v1_GangSchedulingManagement_To_v1alpha1_GangSchedulingManagement(in *v1.GangSchedulingManagement, out *GangSchedulingManagement, s conversion.Scope) error {
	*out = *(*GangSchedulingManagement)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_GangSchedulingManagement_To_v1alpha1_GangSchedulingManagement is an autogenerated conversion function.
func Convert_v1_GangSchedulingManagement_To_v1alpha1_GangSchedulingManagement(in *v1.GangSchedulingManagement, out *GangSchedulingManagement, s conversion.Scope) error {
	return autoConvert_v1_GangSchedulingManagement_To_v1alpha1_GangSchedulingManagement(in, out, s)
}

func autoConvert_v1alpha1_InternalCertManagement_To_v1_InternalCertManagement(in *InternalCertManagement, out *v1.InternalCertManagement, s conversion.Scope) error {
	*out = *(*v1.InternalCertManagement)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_InternalCertManagement_To_v1_InternalCertManagement is an autogenerated conversion function.
func Convert_v1alpha1_InternalCertManagement_To_v1_InternalCertManagement(in *InternalCertManagement, out *v1.InternalCertManagement, s conversion.Scope) error {
	return autoConvert_v1alpha1_InternalCertManagement_To_v1_InternalCertManagement(in, out, s)
}

func autoConvert_v1_InternalCertManagement_To_v1alpha1_InternalCertManagement(in *v1.InternalCertManagement, out *InternalCertManagement, s conversion.Scope) error {
	*out = *(*InternalCertManagement)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_InternalCertManagement_To_v1alpha1_InternalCertManagement is an autogenerated conversion function.
func Convert_v1_InternalCertManagement_To_v1alpha1_InternalCertManagement(in *v1.InternalCertManagement, out *InternalCertManagement, s conversion.Scope) error {
	return autoConvert_v1_InternalCertManagement_To_v1alpha1_InternalCertManagement(in, out, s)
}

func autoConvert_v1alpha1_TLSOptions_To_v1_TLSOptions(in *TLSOptions, out *v1.TLSOptions, s conversion.Scope) error {
	*out = *(*v1.TLSOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_TLSOptions_To_v1_TLSOptions is an autogenerated conversion function.
func Convert_v1alpha1_TLSOptions_To_v1_TLSOptions(in *TLSOptions, out *v1.TLSOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSOptions_To_v1_TLSOptions(in, out, s)
}

func autoConvert_v1_TLSOptions_To_v1alpha1_TLSOptions(in *v1.TLSOptions, out *TLSOptions, s conversion.Scope) error {
	*out = *(*TLSOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_TLSOptions_To_v1alpha1_TLSOptions is an autogenerated conversion function.
func Convert_v1_TLSOptions_To_v1alpha1_TLSOptions(in *v1.TLSOptions, out *TLSOptions, s conversion.Scope) error {
	return autoConvert_v1_TLSOptions_To_v1alpha1_TLSOptions(in, out, s)
}
