apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: manager-rolebinding
    {{- include "lws.labels" . | nindent 4 }}
  name: {{ include "lws.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lws.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "lws.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: proxy-rolebinding
    {{- include "lws.labels" . | nindent 4 }}
  name: {{ include "lws.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lws.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "lws.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}