apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: leader-election-rolebinding
    {{- include "lws.labels" . | nindent 4 }}
  name: {{ include "lws.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lws.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "lws.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}