apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lws.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: controller-manager-sa
    {{- include "lws.labels" . | nindent 4 }}
