- op: replace
  path: /webhooks/1
  value:
    admissionReviewVersions:
    - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate--v1-pod
    failurePolicy: Fail
    name: vpod.kb.io
    objectSelector:
      matchExpressions:
      - key: leaderworkerset.sigs.k8s.io/name
        operator: Exists
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
    sideEffects: None