apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  # annotations:
  #   scheduling.volcano.sh/queue-name: lws-queue # Uncomment the annotation to set the queue name if needed
  #   volcano.sh/sla-waiting-time: 5m  # PodGroups can inherit annotations with the prefix volcano.sh/. 
  name: lws-sample-volcano
spec:
  replicas: 2
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      spec:
        schedulerName: volcano # Need to set the scheduler name to Volcano
        containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
            - containerPort: 8080