# permissions for end users to view leaderworkersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: leaderworkerset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: leader-worker-set
    app.kubernetes.io/part-of: leader-worker-set
    app.kubernetes.io/managed-by: kustomize
  name: leaderworkerset-viewer-role
rules:
- apiGroups:
  - leaderworkerset.x-k8s.io
  resources:
  - leaderworkersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - leaderworkerset.x-k8s.io
  resources:
  - leaderworkersets/status
  verbs:
  - get
