# This file provides RBAC permissions for volcano gang scheduling.
# To enable volcano gang scheduling, uncomment this file in kustomization.yaml
# and ensure gangSchedulingManagement.schedulerProvider is set to "volcano" in controller configuration.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lws-volcano-role
rules:
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - podgroups
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lws-volcano-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lws-volcano-role
subjects:
- kind: ServiceAccount
  name: lws-controller-manager
  namespace: system