apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  labels:
    app.kubernetes.io/name: leaderworkerset
    app.kubernetes.io/instance: leaderworkerset-sample
    app.kubernetes.io/part-of: leader-worker-set
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: leader-worker-set
  name: leaderworkerset-sample
spec:
  replicas: 3
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      spec:
        nodeSelector:
          cloud.google.com/gke-tpu-topology: 4x4
          cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              google.com/tpu: 4
            requests:
              google.com/tpu: 4
          #image: invalid-image
          ports:
          - containerPort: 8080
