apiVersion: lws.x-k8s.io/v1alpha1
kind: Configuration
metadata:
  labels:
    app.kubernetes.io/name: configuration
    app.kubernetes.io/instance: configuration-sample
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lws
  name: configuration-sample
spec:
  # TODO(user): Add fields here
