/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GangSchedulingConfigApplyConfiguration represents a declarative configuration of the GangSchedulingConfig type for use
// with apply.
//
// GangSchedulingConfig defines the gang scheduling configuration of the group
type GangSchedulingConfigApplyConfiguration struct {
	// enable specifies whether to create PodGroups and inject gang scheduling metadata.
	// Defaults to true when this struct is present, or if left unset in the presence of a global scheduler provider.
	Enable *bool `json:"enable,omitempty"`
}

// GangSchedulingConfigApplyConfiguration constructs a declarative configuration of the GangSchedulingConfig type for use with
// apply.
func GangSchedulingConfig() *GangSchedulingConfigApplyConfiguration {
	return &GangSchedulingConfigApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *GangSchedulingConfigApplyConfiguration) WithEnable(value bool) *GangSchedulingConfigApplyConfiguration {
	b.Enable = &value
	return b
}
