/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// InPlaceGroupRestartConfigApplyConfiguration represents a declarative configuration of the InPlaceGroupRestartConfig type for use
// with apply.
//
// InPlaceGroupRestartConfig configures the escalation behavior and triggers for InPlaceGroupRestart.
type InPlaceGroupRestartConfigApplyConfiguration struct {
	// triggers specify which container failures initiate a group restart.
	Triggers []InPlaceGroupRestartTriggerApplyConfiguration `json:"triggers,omitempty"`
	// maxAttempts is the maximum number of in-place restarts a single group may undergo
	// within the window before the controller escalates to full group recreation.
	MaxAttempts *int32 `json:"maxAttempts,omitempty"`
	// windowSeconds is the rolling time window in seconds over which MaxAttempts is counted.
	WindowSeconds *int32 `json:"windowSeconds,omitempty"`
	// recoveryTimeoutSeconds is the maximum duration in seconds allowed for one
	// coordinated in-place restart attempt.
	RecoveryTimeoutSeconds *int32 `json:"recoveryTimeoutSeconds,omitempty"`
}

// InPlaceGroupRestartConfigApplyConfiguration constructs a declarative configuration of the InPlaceGroupRestartConfig type for use with
// apply.
func InPlaceGroupRestartConfig() *InPlaceGroupRestartConfigApplyConfiguration {
	return &InPlaceGroupRestartConfigApplyConfiguration{}
}

// WithTriggers adds the given value to the Triggers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Triggers field.
func (b *InPlaceGroupRestartConfigApplyConfiguration) WithTriggers(values ...*InPlaceGroupRestartTriggerApplyConfiguration) *InPlaceGroupRestartConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTriggers")
		}
		b.Triggers = append(b.Triggers, *values[i])
	}
	return b
}

// WithMaxAttempts sets the MaxAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAttempts field is set to the value of the last call.
func (b *InPlaceGroupRestartConfigApplyConfiguration) WithMaxAttempts(value int32) *InPlaceGroupRestartConfigApplyConfiguration {
	b.MaxAttempts = &value
	return b
}

// WithWindowSeconds sets the WindowSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WindowSeconds field is set to the value of the last call.
func (b *InPlaceGroupRestartConfigApplyConfiguration) WithWindowSeconds(value int32) *InPlaceGroupRestartConfigApplyConfiguration {
	b.WindowSeconds = &value
	return b
}

// WithRecoveryTimeoutSeconds sets the RecoveryTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryTimeoutSeconds field is set to the value of the last call.
func (b *InPlaceGroupRestartConfigApplyConfiguration) WithRecoveryTimeoutSeconds(value int32) *InPlaceGroupRestartConfigApplyConfiguration {
	b.RecoveryTimeoutSeconds = &value
	return b
}
