/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	leaderworkersetv1 "sigs.k8s.io/lws/api/leaderworkerset/v1"
)

// InPlaceGroupRestartTriggerApplyConfiguration represents a declarative configuration of the InPlaceGroupRestartTrigger type for use
// with apply.
//
// InPlaceGroupRestartTrigger defines which container exits trigger a group restart.
type InPlaceGroupRestartTriggerApplyConfiguration struct {
	// role indicates whether the container exists in the Leader, Worker, or Both.
	Role *leaderworkersetv1.PodRole `json:"role,omitempty"`
	// containerName specifies which container's failure initiates a group restart.
	ContainerName *string `json:"containerName,omitempty"`
	// recoverableExitCodes are the exit codes that natively trigger RestartAllContainers.
	RecoverableExitCodes []int32 `json:"recoverableExitCodes,omitempty"`
}

// InPlaceGroupRestartTriggerApplyConfiguration constructs a declarative configuration of the InPlaceGroupRestartTrigger type for use with
// apply.
func InPlaceGroupRestartTrigger() *InPlaceGroupRestartTriggerApplyConfiguration {
	return &InPlaceGroupRestartTriggerApplyConfiguration{}
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *InPlaceGroupRestartTriggerApplyConfiguration) WithRole(value leaderworkersetv1.PodRole) *InPlaceGroupRestartTriggerApplyConfiguration {
	b.Role = &value
	return b
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *InPlaceGroupRestartTriggerApplyConfiguration) WithContainerName(value string) *InPlaceGroupRestartTriggerApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithRecoverableExitCodes adds the given value to the RecoverableExitCodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RecoverableExitCodes field.
func (b *InPlaceGroupRestartTriggerApplyConfiguration) WithRecoverableExitCodes(values ...int32) *InPlaceGroupRestartTriggerApplyConfiguration {
	for i := range values {
		b.RecoverableExitCodes = append(b.RecoverableExitCodes, values[i])
	}
	return b
}
