/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1alpha3 "k8s.io/client-go/applyconfigurations/scheduling/v1alpha3"
)

// LeaderWorkerSetWorkerSchedulingApplyConfiguration represents a declarative configuration of the LeaderWorkerSetWorkerScheduling type for use
// with apply.
//
// LeaderWorkerSetWorkerScheduling defines scheduling for the worker leaf
// PodGroup. It is a distinct type so worker-specific fields can evolve without
// changing leader scheduling.
type LeaderWorkerSetWorkerSchedulingApplyConfiguration struct {
	// schedulingPolicy defines scheduling for the worker PodGroup.
	// Immutable after creation.
	SchedulingPolicy *v1alpha3.WorkloadPodGroupSchedulingPolicyApplyConfiguration `json:"schedulingPolicy,omitempty"`
	// schedulingConstraints defines placement constraints for the worker PodGroup.
	// Immutable after creation.
	SchedulingConstraints *v1alpha3.WorkloadPodGroupSchedulingConstraintsApplyConfiguration `json:"schedulingConstraints,omitempty"`
	// disruptionMode controls how worker pods may be disrupted.
	// Immutable after creation.
	DisruptionMode *v1alpha3.WorkloadPodGroupDisruptionModeApplyConfiguration `json:"disruptionMode,omitempty"`
	// resourceClaims lists dynamic resource claims shared by worker pods.
	// Immutable after creation.
	ResourceClaims []v1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration `json:"resourceClaims,omitempty"`
}

// LeaderWorkerSetWorkerSchedulingApplyConfiguration constructs a declarative configuration of the LeaderWorkerSetWorkerScheduling type for use with
// apply.
func LeaderWorkerSetWorkerScheduling() *LeaderWorkerSetWorkerSchedulingApplyConfiguration {
	return &LeaderWorkerSetWorkerSchedulingApplyConfiguration{}
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *LeaderWorkerSetWorkerSchedulingApplyConfiguration) WithSchedulingPolicy(value *v1alpha3.WorkloadPodGroupSchedulingPolicyApplyConfiguration) *LeaderWorkerSetWorkerSchedulingApplyConfiguration {
	b.SchedulingPolicy = value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *LeaderWorkerSetWorkerSchedulingApplyConfiguration) WithSchedulingConstraints(value *v1alpha3.WorkloadPodGroupSchedulingConstraintsApplyConfiguration) *LeaderWorkerSetWorkerSchedulingApplyConfiguration {
	b.SchedulingConstraints = value
	return b
}

// WithDisruptionMode sets the DisruptionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionMode field is set to the value of the last call.
func (b *LeaderWorkerSetWorkerSchedulingApplyConfiguration) WithDisruptionMode(value *v1alpha3.WorkloadPodGroupDisruptionModeApplyConfiguration) *LeaderWorkerSetWorkerSchedulingApplyConfiguration {
	b.DisruptionMode = value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *LeaderWorkerSetWorkerSchedulingApplyConfiguration) WithResourceClaims(values ...*v1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration) *LeaderWorkerSetWorkerSchedulingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceClaims")
		}
		b.ResourceClaims = append(b.ResourceClaims, *values[i])
	}
	return b
}
