/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	leaderworkersetv1 "sigs.k8s.io/lws/api/leaderworkerset/v1"
)

// LeaderWorkerSetSpecApplyConfiguration represents a declarative configuration of the LeaderWorkerSetSpec type for use
// with apply.
//
// One group consists of a single leader and M workers, and the total number of pods in a group is M+1.
// LeaderWorkerSet will create N replicas of leader-worker pod groups (hereinafter referred to as group).
//
// Each group has a unique index between 0 and N-1. We call this the leaderIndex.
// The leaderIndex is used to uniquely name the leader pod of each group in the following format:
// leaderWorkerSetName-leaderIndex. This is considered as the name of the group too.
//
// Each worker pod in the group has a unique workerIndex between 1 and M. The leader also
// gets a workerIndex, and it is always set to 0.
// Worker pods are named using the format: leaderWorkerSetName-leaderIndex-workerIndex.
type LeaderWorkerSetSpecApplyConfiguration struct {
	// Number of leader-workers groups. A scale subresource is available to enable HPA. The
	// selector for HPA will be that of the leader pod, and so practically HPA will be looking up the
	// leader pod metrics. Note that the leader pod could aggregate metrics from
	// the rest of the group and expose them as a summary custom metric representing the whole
	// group.
	// On scale down, the leader pod as well as the workers statefulset will be deleted.
	// Default to 1.
	Replicas *int32 `json:"replicas,omitempty"`
	// LeaderWorkerTemplate defines the template for leader/worker pods
	LeaderWorkerTemplate *LeaderWorkerTemplateApplyConfiguration `json:"leaderWorkerTemplate,omitempty"`
	// RolloutStrategy defines the strategy that will be applied to update replicas
	// when a revision is made to the leaderWorkerTemplate.
	RolloutStrategy *RolloutStrategyApplyConfiguration `json:"rolloutStrategy,omitempty"`
	// StartupPolicy determines the startup policy for the worker statefulset.
	StartupPolicy *leaderworkersetv1.StartupPolicyType `json:"startupPolicy,omitempty"`
	// NetworkConfig defines the network configuration of the group
	NetworkConfig *NetworkConfigApplyConfiguration `json:"networkConfig,omitempty"`
}

// LeaderWorkerSetSpecApplyConfiguration constructs a declarative configuration of the LeaderWorkerSetSpec type for use with
// apply.
func LeaderWorkerSetSpec() *LeaderWorkerSetSpecApplyConfiguration {
	return &LeaderWorkerSetSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *LeaderWorkerSetSpecApplyConfiguration) WithReplicas(value int32) *LeaderWorkerSetSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithLeaderWorkerTemplate sets the LeaderWorkerTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderWorkerTemplate field is set to the value of the last call.
func (b *LeaderWorkerSetSpecApplyConfiguration) WithLeaderWorkerTemplate(value *LeaderWorkerTemplateApplyConfiguration) *LeaderWorkerSetSpecApplyConfiguration {
	b.LeaderWorkerTemplate = value
	return b
}

// WithRolloutStrategy sets the RolloutStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RolloutStrategy field is set to the value of the last call.
func (b *LeaderWorkerSetSpecApplyConfiguration) WithRolloutStrategy(value *RolloutStrategyApplyConfiguration) *LeaderWorkerSetSpecApplyConfiguration {
	b.RolloutStrategy = value
	return b
}

// WithStartupPolicy sets the StartupPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartupPolicy field is set to the value of the last call.
func (b *LeaderWorkerSetSpecApplyConfiguration) WithStartupPolicy(value leaderworkersetv1.StartupPolicyType) *LeaderWorkerSetSpecApplyConfiguration {
	b.StartupPolicy = &value
	return b
}

// WithNetworkConfig sets the NetworkConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkConfig field is set to the value of the last call.
func (b *LeaderWorkerSetSpecApplyConfiguration) WithNetworkConfig(value *NetworkConfigApplyConfiguration) *LeaderWorkerSetSpecApplyConfiguration {
	b.NetworkConfig = value
	return b
}
