/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1alpha3 "k8s.io/api/scheduling/v1alpha3"
	schedulingv1alpha3 "k8s.io/client-go/applyconfigurations/scheduling/v1alpha3"
)

// LeaderWorkerSetReplicaSchedulingApplyConfiguration represents a declarative configuration of the LeaderWorkerSetReplicaScheduling type for use
// with apply.
//
// LeaderWorkerSetReplicaScheduling defines scheduling for a leader and its
// workers. In phase 1 it is either lowered to one flat PodGroup per replica or
// its leader and worker leaves are materialized independently.
type LeaderWorkerSetReplicaSchedulingApplyConfiguration struct {
	// schedulingPolicy defines scheduling for a leader and its workers.
	// Immutable after creation.
	SchedulingPolicy *v1alpha3.WorkloadCompositePodGroupSchedulingPolicy `json:"schedulingPolicy,omitempty"`
	// schedulingConstraints defines placement constraints for a replica.
	// Immutable after creation.
	SchedulingConstraints *v1alpha3.WorkloadCompositePodGroupSchedulingConstraints `json:"schedulingConstraints,omitempty"`
	// disruptionMode controls how the leader and worker groups may be disrupted.
	// Immutable after creation.
	DisruptionMode *v1alpha3.WorkloadCompositePodGroupDisruptionMode `json:"disruptionMode,omitempty"`
	// resourceClaims lists dynamic resource claims shared by replica members.
	// It is mutually exclusive with leader and worker scheduling leaves.
	// Immutable after creation.
	ResourceClaims []schedulingv1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration `json:"resourceClaims,omitempty"`
	// leader defines level-3 scheduling for the leader PodGroup.
	Leader *LeaderWorkerSetLeaderSchedulingApplyConfiguration `json:"leader,omitempty"`
	// worker defines level-3 scheduling for the worker PodGroup.
	Worker *LeaderWorkerSetWorkerSchedulingApplyConfiguration `json:"worker,omitempty"`
}

// LeaderWorkerSetReplicaSchedulingApplyConfiguration constructs a declarative configuration of the LeaderWorkerSetReplicaScheduling type for use with
// apply.
func LeaderWorkerSetReplicaScheduling() *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	return &LeaderWorkerSetReplicaSchedulingApplyConfiguration{}
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithSchedulingPolicy(value v1alpha3.WorkloadCompositePodGroupSchedulingPolicy) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	b.SchedulingPolicy = &value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithSchedulingConstraints(value v1alpha3.WorkloadCompositePodGroupSchedulingConstraints) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	b.SchedulingConstraints = &value
	return b
}

// WithDisruptionMode sets the DisruptionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionMode field is set to the value of the last call.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithDisruptionMode(value v1alpha3.WorkloadCompositePodGroupDisruptionMode) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	b.DisruptionMode = &value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithResourceClaims(values ...*schedulingv1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceClaims")
		}
		b.ResourceClaims = append(b.ResourceClaims, *values[i])
	}
	return b
}

// WithLeader sets the Leader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Leader field is set to the value of the last call.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithLeader(value *LeaderWorkerSetLeaderSchedulingApplyConfiguration) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	b.Leader = value
	return b
}

// WithWorker sets the Worker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Worker field is set to the value of the last call.
func (b *LeaderWorkerSetReplicaSchedulingApplyConfiguration) WithWorker(value *LeaderWorkerSetWorkerSchedulingApplyConfiguration) *LeaderWorkerSetReplicaSchedulingApplyConfiguration {
	b.Worker = value
	return b
}
