/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1alpha3 "k8s.io/api/scheduling/v1alpha3"
	schedulingv1alpha3 "k8s.io/client-go/applyconfigurations/scheduling/v1alpha3"
)

// LeaderWorkerSetSchedulingApplyConfiguration represents a declarative configuration of the LeaderWorkerSetScheduling type for use
// with apply.
//
// LeaderWorkerSetScheduling defines level-1 scheduling for the complete LWS.
type LeaderWorkerSetSchedulingApplyConfiguration struct {
	// schedulingPolicy defines scheduling for all replicas in the LWS. In
	// phase 1 this level is lowered to one flat PodGroup.
	// Immutable after creation.
	SchedulingPolicy *v1alpha3.WorkloadCompositePodGroupSchedulingPolicy `json:"schedulingPolicy,omitempty"`
	// schedulingConstraints defines placement constraints for all replicas.
	// Immutable after creation.
	SchedulingConstraints *v1alpha3.WorkloadCompositePodGroupSchedulingConstraints `json:"schedulingConstraints,omitempty"`
	// disruptionMode controls how replica groups may be disrupted.
	// Immutable after creation.
	DisruptionMode *v1alpha3.WorkloadCompositePodGroupDisruptionMode `json:"disruptionMode,omitempty"`
	// resourceClaims lists dynamic resource claims shared by pods across the
	// LWS. In phase 1 this is supported only when this level is lowered to a
	// flat PodGroup, and is mutually exclusive with replica scheduling.
	// Immutable after creation.
	ResourceClaims []schedulingv1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration `json:"resourceClaims,omitempty"`
	// replica defines level-2 scheduling for each LWS replica.
	Replica *LeaderWorkerSetReplicaSchedulingApplyConfiguration `json:"replica,omitempty"`
}

// LeaderWorkerSetSchedulingApplyConfiguration constructs a declarative configuration of the LeaderWorkerSetScheduling type for use with
// apply.
func LeaderWorkerSetScheduling() *LeaderWorkerSetSchedulingApplyConfiguration {
	return &LeaderWorkerSetSchedulingApplyConfiguration{}
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *LeaderWorkerSetSchedulingApplyConfiguration) WithSchedulingPolicy(value v1alpha3.WorkloadCompositePodGroupSchedulingPolicy) *LeaderWorkerSetSchedulingApplyConfiguration {
	b.SchedulingPolicy = &value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *LeaderWorkerSetSchedulingApplyConfiguration) WithSchedulingConstraints(value v1alpha3.WorkloadCompositePodGroupSchedulingConstraints) *LeaderWorkerSetSchedulingApplyConfiguration {
	b.SchedulingConstraints = &value
	return b
}

// WithDisruptionMode sets the DisruptionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionMode field is set to the value of the last call.
func (b *LeaderWorkerSetSchedulingApplyConfiguration) WithDisruptionMode(value v1alpha3.WorkloadCompositePodGroupDisruptionMode) *LeaderWorkerSetSchedulingApplyConfiguration {
	b.DisruptionMode = &value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *LeaderWorkerSetSchedulingApplyConfiguration) WithResourceClaims(values ...*schedulingv1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration) *LeaderWorkerSetSchedulingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceClaims")
		}
		b.ResourceClaims = append(b.ResourceClaims, *values[i])
	}
	return b
}

// WithReplica sets the Replica field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replica field is set to the value of the last call.
func (b *LeaderWorkerSetSchedulingApplyConfiguration) WithReplica(value *LeaderWorkerSetReplicaSchedulingApplyConfiguration) *LeaderWorkerSetSchedulingApplyConfiguration {
	b.Replica = value
	return b
}
