/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	appsv1 "k8s.io/api/apps/v1"
	apicorev1 "k8s.io/api/core/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
	leaderworkersetv1 "sigs.k8s.io/lws/api/leaderworkerset/v1"
)

// LeaderWorkerTemplateApplyConfiguration represents a declarative configuration of the LeaderWorkerTemplate type for use
// with apply.
//
// Template of the leader/worker pods, the group will include at least one leader pod.
// Defaults to the worker template if not specified. The idea is to allow users to create a
// group with identical templates without needing to specify the template in both places.
// For the leader it represents the id of the group, while for the workers it represents the
// index within the group. For this reason, users should depend on the labels injected by this
// API whenever possible.
type LeaderWorkerTemplateApplyConfiguration struct {
	// LeaderTemplate defines the pod template for leader pods.
	LeaderTemplate *corev1.PodTemplateSpecApplyConfiguration `json:"leaderTemplate,omitempty"`
	// WorkerTemplate defines the pod template for worker pods.
	WorkerTemplate *corev1.PodTemplateSpecApplyConfiguration `json:"workerTemplate,omitempty"`
	// Number of pods to create. It is the total number of pods in each group.
	// The minimum is 1 which represent the leader. When set to 1, the leader
	// pod is created for each group as well as a 0-replica StatefulSet for the workers.
	// Default to 1.
	Size *int32 `json:"size,omitempty"`
	// RestartPolicy defines the restart policy when pod failures happen.
	// The former named Default policy is deprecated, will be removed in the future,
	// replace with None policy for the same behavior.
	RestartPolicy *leaderworkersetv1.RestartPolicyType `json:"restartPolicy,omitempty"`
	// SubGroupPolicy describes the policy that will be applied when creating subgroups
	// in each replica.
	SubGroupPolicy *SubGroupPolicyApplyConfiguration `json:"subGroupPolicy,omitempty"`
	// VolumeClaimTemplates is a list of claims that pods are allowed to reference.
	// Every claim in this list must have at least one matching (by name) volumeMount
	// in one container in the template. A claim in this list takes precedence over
	// any volumes in the template, with the same name.
	VolumeClaimTemplates []apicorev1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty"`
	// PersistentVolumeClaimRetentionPolicy describes the policy used for PVCs created from
	// the VolumeClaimTemplates.
	PersistentVolumeClaimRetentionPolicy *appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy `json:"persistentVolumeClaimRetentionPolicy,omitempty"`
}

// LeaderWorkerTemplateApplyConfiguration constructs a declarative configuration of the LeaderWorkerTemplate type for use with
// apply.
func LeaderWorkerTemplate() *LeaderWorkerTemplateApplyConfiguration {
	return &LeaderWorkerTemplateApplyConfiguration{}
}

// WithLeaderTemplate sets the LeaderTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaderTemplate field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithLeaderTemplate(value *corev1.PodTemplateSpecApplyConfiguration) *LeaderWorkerTemplateApplyConfiguration {
	b.LeaderTemplate = value
	return b
}

// WithWorkerTemplate sets the WorkerTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkerTemplate field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithWorkerTemplate(value *corev1.PodTemplateSpecApplyConfiguration) *LeaderWorkerTemplateApplyConfiguration {
	b.WorkerTemplate = value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithSize(value int32) *LeaderWorkerTemplateApplyConfiguration {
	b.Size = &value
	return b
}

// WithRestartPolicy sets the RestartPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartPolicy field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithRestartPolicy(value leaderworkersetv1.RestartPolicyType) *LeaderWorkerTemplateApplyConfiguration {
	b.RestartPolicy = &value
	return b
}

// WithSubGroupPolicy sets the SubGroupPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupPolicy field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithSubGroupPolicy(value *SubGroupPolicyApplyConfiguration) *LeaderWorkerTemplateApplyConfiguration {
	b.SubGroupPolicy = value
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *LeaderWorkerTemplateApplyConfiguration) WithVolumeClaimTemplates(values ...apicorev1.PersistentVolumeClaim) *LeaderWorkerTemplateApplyConfiguration {
	for i := range values {
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, values[i])
	}
	return b
}

// WithPersistentVolumeClaimRetentionPolicy sets the PersistentVolumeClaimRetentionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentVolumeClaimRetentionPolicy field is set to the value of the last call.
func (b *LeaderWorkerTemplateApplyConfiguration) WithPersistentVolumeClaimRetentionPolicy(value appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy) *LeaderWorkerTemplateApplyConfiguration {
	b.PersistentVolumeClaimRetentionPolicy = &value
	return b
}
