/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1alpha3 "k8s.io/client-go/applyconfigurations/scheduling/v1alpha3"
)

// LeaderWorkerSetPodGroupSchedulingApplyConfiguration represents a declarative configuration of the LeaderWorkerSetPodGroupScheduling type for use
// with apply.
//
// LeaderWorkerSetPodGroupScheduling defines scheduling for one leaf PodGroup.
type LeaderWorkerSetPodGroupSchedulingApplyConfiguration struct {
	SchedulingPolicy      *v1alpha3.WorkloadPodGroupSchedulingPolicyApplyConfiguration      `json:"schedulingPolicy,omitempty"`
	SchedulingConstraints *v1alpha3.WorkloadPodGroupSchedulingConstraintsApplyConfiguration `json:"schedulingConstraints,omitempty"`
	DisruptionMode        *v1alpha3.WorkloadPodGroupDisruptionModeApplyConfiguration        `json:"disruptionMode,omitempty"`
	ResourceClaims        []v1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration        `json:"resourceClaims,omitempty"`
}

// LeaderWorkerSetPodGroupSchedulingApplyConfiguration constructs a declarative configuration of the LeaderWorkerSetPodGroupScheduling type for use with
// apply.
func LeaderWorkerSetPodGroupScheduling() *LeaderWorkerSetPodGroupSchedulingApplyConfiguration {
	return &LeaderWorkerSetPodGroupSchedulingApplyConfiguration{}
}

// WithSchedulingPolicy sets the SchedulingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingPolicy field is set to the value of the last call.
func (b *LeaderWorkerSetPodGroupSchedulingApplyConfiguration) WithSchedulingPolicy(value *v1alpha3.WorkloadPodGroupSchedulingPolicyApplyConfiguration) *LeaderWorkerSetPodGroupSchedulingApplyConfiguration {
	b.SchedulingPolicy = value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *LeaderWorkerSetPodGroupSchedulingApplyConfiguration) WithSchedulingConstraints(value *v1alpha3.WorkloadPodGroupSchedulingConstraintsApplyConfiguration) *LeaderWorkerSetPodGroupSchedulingApplyConfiguration {
	b.SchedulingConstraints = value
	return b
}

// WithDisruptionMode sets the DisruptionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionMode field is set to the value of the last call.
func (b *LeaderWorkerSetPodGroupSchedulingApplyConfiguration) WithDisruptionMode(value *v1alpha3.WorkloadPodGroupDisruptionModeApplyConfiguration) *LeaderWorkerSetPodGroupSchedulingApplyConfiguration {
	b.DisruptionMode = value
	return b
}

// WithResourceClaims adds the given value to the ResourceClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceClaims field.
func (b *LeaderWorkerSetPodGroupSchedulingApplyConfiguration) WithResourceClaims(values ...*v1alpha3.WorkloadPodGroupResourceClaimApplyConfiguration) *LeaderWorkerSetPodGroupSchedulingApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceClaims")
		}
		b.ResourceClaims = append(b.ResourceClaims, *values[i])
	}
	return b
}
