/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RestartBackoffApplyConfiguration represents a declarative configuration of the RestartBackoff type for use
// with apply.
//
// RestartBackoff defines the exponential backoff configuration for group recreation.
type RestartBackoffApplyConfiguration struct {
	// base is the initial backoff delay before group recreation.
	// Defaults to 10s.
	Base *metav1.Duration `json:"base,omitempty"`
	// cap is the maximum backoff delay before group recreation.
	// Defaults to 5m.
	Cap *metav1.Duration `json:"cap,omitempty"`
}

// RestartBackoffApplyConfiguration constructs a declarative configuration of the RestartBackoff type for use with
// apply.
func RestartBackoff() *RestartBackoffApplyConfiguration {
	return &RestartBackoffApplyConfiguration{}
}

// WithBase sets the Base field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Base field is set to the value of the last call.
func (b *RestartBackoffApplyConfiguration) WithBase(value metav1.Duration) *RestartBackoffApplyConfiguration {
	b.Base = &value
	return b
}

// WithCap sets the Cap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cap field is set to the value of the last call.
func (b *RestartBackoffApplyConfiguration) WithCap(value metav1.Duration) *RestartBackoffApplyConfiguration {
	b.Cap = &value
	return b
}
