/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RestartBackoffApplyConfiguration represents a declarative configuration of the RestartBackoff type for use
// with apply.
//
// RestartBackoff defines the exponential backoff configuration for group recreation.
type RestartBackoffApplyConfiguration struct {
	// baseSeconds is the initial backoff delay in seconds before group recreation.
	// Defaults to 10.
	BaseSeconds *int32 `json:"baseSeconds,omitempty"`
	// capSeconds is the maximum backoff delay in seconds before group recreation.
	// Defaults to 300.
	CapSeconds *int32 `json:"capSeconds,omitempty"`
}

// RestartBackoffApplyConfiguration constructs a declarative configuration of the RestartBackoff type for use with
// apply.
func RestartBackoff() *RestartBackoffApplyConfiguration {
	return &RestartBackoffApplyConfiguration{}
}

// WithBaseSeconds sets the BaseSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseSeconds field is set to the value of the last call.
func (b *RestartBackoffApplyConfiguration) WithBaseSeconds(value int32) *RestartBackoffApplyConfiguration {
	b.BaseSeconds = &value
	return b
}

// WithCapSeconds sets the CapSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapSeconds field is set to the value of the last call.
func (b *RestartBackoffApplyConfiguration) WithCapSeconds(value int32) *RestartBackoffApplyConfiguration {
	b.CapSeconds = &value
	return b
}
