/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	leaderworkersetv1 "sigs.k8s.io/lws/api/leaderworkerset/v1"
)

// SubGroupPolicyApplyConfiguration represents a declarative configuration of the SubGroupPolicy type for use
// with apply.
//
// SubGroupPolicy describes the policy that will be applied when creating subgroups.
type SubGroupPolicyApplyConfiguration struct {
	// Defines what type of Subgroups to create. Defaults to
	// LeaderWorker
	Type *leaderworkersetv1.SubGroupPolicyType `json:"subGroupPolicyType,omitempty"`
	// The number of pods per subgroup. This value is immutable,
	// and must not be greater than LeaderWorkerSet.Spec.Size.
	// Size must be divisible by subGroupSize in which case the
	// subgroups will be of equal size. Or size - 1 is divisible
	// by subGroupSize, in which case the leader is considered as
	// the extra pod, and will be part of the first subgroup.
	SubGroupSize *int32 `json:"subGroupSize,omitempty"`
}

// SubGroupPolicyApplyConfiguration constructs a declarative configuration of the SubGroupPolicy type for use with
// apply.
func SubGroupPolicy() *SubGroupPolicyApplyConfiguration {
	return &SubGroupPolicyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SubGroupPolicyApplyConfiguration) WithType(value leaderworkersetv1.SubGroupPolicyType) *SubGroupPolicyApplyConfiguration {
	b.Type = &value
	return b
}

// WithSubGroupSize sets the SubGroupSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupSize field is set to the value of the last call.
func (b *SubGroupPolicyApplyConfiguration) WithSubGroupSize(value int32) *SubGroupPolicyApplyConfiguration {
	b.SubGroupSize = &value
	return b
}
