apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lws-memory-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: leaderworkerset.x-k8s.io/v1
    kind: LeaderWorkerSet
    name: leaderworkerset-sample
