name: Send Unit Test Coverage 
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Build Test
      run: go test -race -covermode=atomic -coverprofile=profile.cov ./pkg/... ./cmd/...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github
