name: Trivy vulnerability scanner
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.6
        id: go

      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build an image from Dockerfile
        run: |
          export IMG=test/lws:latest
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export OUTPUT_TYPE=registry
          make build
          make image-build

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'test/lws:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
