---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-disaggregatedset-x-k8s-io-v1alpha1-disaggregatedset
  failurePolicy: Fail
  name: vdisaggregatedset.kb.io
  rules:
  - apiGroups:
    - disaggregatedset.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - disaggregatedsets
  sideEffects: None
